[Cooking fat]
label = "Cooking Fat"
stock = 1000
price = 1950

[fat.cart]
quantity = 15

[[fat.terms]]
size = 5
discount = 3


[Ajab flour 2kg]
label = "Flour"
stock = 1000
price = 2100

[flour.cart]
quantity = 100

[[flour.terms]]
size = 20
discount = 2.5
